spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hack?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&characterEncoding=UTF-8
    username: hack
    password: hack
#    url: jdbc:mysql://seongho-rds.cpjoxjpm1vci.ap-northeast-2.rds.amazonaws.com:3306/hack?useSSL=false&allowPublicKeyRetrieval=true&&characterEncoding=UTF-8&serverTimezone=UTC
#    username: hack
#    password: hack
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    open-in-view: false
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 500
        dialect:
          storage_engine: innodb

